# -*- coding: utf-8 -*-
"""Rachel_Phung_MIS373_A2_Part2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mo1RT_pbXFm4o7ixTYKZsoCU1BmQpL9n

# MIS373 A2 Part 2 - Waste Image Classification

Student name: Ngoc Anh (Rachel) Phung

Student ID: 224598824
"""

import os, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (Flatten, Dense, Dropout, Conv2D,
                                     MaxPooling2D, BatchNormalization,
                                     GlobalAveragePooling2D, Input,
                                     SpatialDropout2D)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.preprocessing.image import ImageDataGenerator

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("TensorFlow:", tf.__version__)

from google.colab import drive
drive.mount('/content/drive')

DATA_DIR = '/content/drive/MyDrive/Colab Notebooks/MIS373/A2 Part 2'  # <-- update this

img_rows, img_cols, channels = 96, 96, 3
num_classes = 6
BATCH_SIZE  = 32

CLASSES = sorted(os.listdir(DATA_DIR))
print("Classes:", CLASSES)
print("Number of classes:", len(CLASSES))

"""## EDA"""

# ── Class distribution ────────────────────────────────────────────────────────
class_counts = {}
for cls in CLASSES:
    class_counts[cls] = len(os.listdir(os.path.join(DATA_DIR, cls)))

plt.figure(figsize=(9, 5))
bars = plt.bar(class_counts.keys(), class_counts.values(),
               color='cornflowerblue')
for bar, val in zip(bars, class_counts.values()):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
             str(val), ha='center', va='bottom', fontweight='bold')
plt.title('Image Count per Waste Class')
plt.xlabel('Class')
plt.ylabel('Number of Images')
plt.tight_layout()
plt.show()

print("\nClass distribution:")
for k, v in class_counts.items():
    print(f"  {k:<12}: {v} images")
print(f"  {'TOTAL':<12}: {sum(class_counts.values())} images")

# ── Sample images per class ───────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(12, 7))
for ax, cls in zip(axes.flatten(), CLASSES):
    cls_path = os.path.join(DATA_DIR, cls)
    img = mpimg.imread(os.path.join(cls_path,
                       random.choice(os.listdir(cls_path))))
    ax.imshow(img)
    ax.set_title(cls.capitalize(), fontsize=13)
    ax.axis('off')
plt.suptitle('Sample Images per Waste Class', fontsize=15)
plt.tight_layout()
plt.show()

"""## Load Images & Split"""

# ── Load all images into memory at 96×96 ─────────────────────────────────────
X, y = [], []

for idx, cls in enumerate(CLASSES):
    cls_path = os.path.join(DATA_DIR, cls)
    for fname in os.listdir(cls_path):
        fpath = os.path.join(cls_path, fname)
        try:
            img = tf.keras.utils.load_img(
                fpath, target_size=(img_rows, img_cols))
            X.append(tf.keras.utils.img_to_array(img))
            y.append(idx)
        except Exception:
            pass

X = np.array(X, dtype='float32') / 255.0
y = np.array(y)

print(f"X shape : {X.shape}")
print(f"y shape : {y.shape}")
print(f"Pixel range: [{X.min():.2f}, {X.max():.2f}]")

# ── 70/30 stratified split ────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=SEED, stratify=y
)

print(f"\nTraining samples : {len(X_train)}")
print(f"Testing  samples : {len(X_test)}")

"""## Augmentation Generators"""

# ── Light augmentation (M1–M6) ────────────────────────────────────────────────
# Horizontal flip + small rotation only.
# Vertical flip excluded — waste items have a natural upright orientation.
datagen_light = ImageDataGenerator(
    horizontal_flip=True,
    rotation_range=15
)
datagen_light.fit(X_train)

# ── Strong augmentation (M7–M8) ───────────────────────────────────────────────
# Adds zoom and brightness jitter to expose the model to more variation.
# Shear and vertical flip still excluded for semantic reasons.
datagen_strong = ImageDataGenerator(
    horizontal_flip=True,
    rotation_range=20,
    zoom_range=0.20,
    brightness_range=[0.8, 1.2],
    width_shift_range=0.10,
    height_shift_range=0.10
)
datagen_strong.fit(X_train)

print("Augmentation generators ready.")

"""## Shared Utilities"""

def get_callbacks(patience_es=10, patience_lr=5):
    return [
        EarlyStopping(monitor='val_loss', patience=patience_es,
                      restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                          patience=patience_lr, min_lr=1e-6, verbose=1)
    ]

def plot_history(history, model_name):
    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    axes[0].plot(history.history['accuracy'],     label='Train')
    axes[0].plot(history.history['val_accuracy'], label='Validation')
    axes[0].set_title(f'{model_name} — Accuracy')
    axes[0].set_xlabel('Epoch')
    axes[0].legend()

    axes[1].plot(history.history['loss'],     label='Train')
    axes[1].plot(history.history['val_loss'], label='Validation')
    axes[1].set_title(f'{model_name} — Loss')
    axes[1].set_xlabel('Epoch')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

def evaluate_model(model, X, y_true, model_name):
    loss, acc = model.evaluate(X, y_true, verbose=0)
    y_pred = np.argmax(model.predict(X, verbose=0), axis=1)

    print(f"\n{'='*60}")
    print(f"  {model_name}")
    print(f"  Test Accuracy : {acc:.4f}  |  Test Loss : {loss:.4f}")
    print('='*60)
    print(classification_report(y_true, y_pred, target_names=CLASSES))

    # Normalised confusion matrix
    cm = confusion_matrix(y_true, y_pred, normalize='true')
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='.2f', cmap='Blues',
                xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title(f'{model_name} — Normalised Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.show()

    return {
        'model'   : model_name,
        'accuracy': acc,
        'loss'    : loss,
        'y_pred'  : y_pred,
        'report'  : classification_report(y_true, y_pred,
                                          target_names=CLASSES,
                                          output_dict=True)
    }

"""## M1 - ANN"""

# ── M1: ANN Baseline ──────────────────────────────────────────────────────────
# Architecture rationale:
#   Treats each pixel as an independent input feature — no spatial awareness.
#   A 96×96×3 image becomes a flat vector of 27,648 values fed directly into
#   a Dense layer. This model cannot detect edges, textures, or shapes because
#   it has no mechanism to relate neighbouring pixels. It serves as a lower-bound
#   baseline: if even this model cannot learn anything, there is a data or
#   preprocessing problem. Expected performance: near random chance (~17%).
#   The gap between M1 and M2 motivates the use of convolutional layers.

def build_m1():
    model = Sequential([
        Flatten(input_shape=(img_rows, img_cols, channels)),
        Dense(128, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M1_ANN_Baseline')
    model.summary()
    return model

m1 = build_m1()
m1.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m1 = m1.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m1, 'M1 — ANN Baseline')
results_m1 = evaluate_model(m1, X_test, y_test, 'M1 — ANN Baseline')

"""## M2 - CNN (1 block)"""

# ── M2: Tiny CNN ──────────────────────────────────────────────────────────────
# Architecture rationale:
#   Introduces a single convolutional block (Conv → Pool) before the dense head.
#   The 3×3 kernel slides across the image preserving spatial relationships
#   between neighbouring pixels — the fundamental advantage of CNNs over ANNs
#   for image data. 32 filters detect 32 distinct low-level features (edges,
#   colour blobs). MaxPooling halves spatial dimensions, providing translation
#   invariance: a cardboard edge detected slightly left or right still activates
#   the same filter. Dropout(0.25) after pooling and Dropout(0.5) in the dense
#   head provide early regularisation. No BatchNorm — deliberately absent to
#   isolate the effect of adding it in M5.

def build_m2():
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', padding='same',
               input_shape=(img_rows, img_cols, channels)),
        MaxPooling2D(2, 2),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M2_Tiny_CNN')
    model.summary()
    return model

m2 = build_m2()
m2.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m2 = m2.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m2, 'M2 — Tiny CNN')
results_m2 = evaluate_model(m2, X_test, y_test, 'M2 — Tiny CNN')

"""## M3 - CNN (3 block, x2 filter)"""

# ── M3: Deeper CNN ────────────────────────────────────────────────────────────
# Architecture rationale:
#   Extends M2 to three convolutional blocks with a standard doubling filter
#   progression (32 → 64 → 128). Each block learns increasingly abstract features:
#   block 1 detects edges and colour gradients; block 2 learns textures (the
#   corrugation of cardboard, the smoothness of glass); block 3 captures
#   object-level patterns (bottle shapes, crumpled surfaces).
#   No dropout or BatchNorm — deliberately omitted to isolate the effect of
#   depth alone. This model is expected to overfit on ~2,000 training images,
#   which motivates the addition of regularisation in M4 and M5.

def build_m3():
    model = Sequential([
        # Block 1
        Conv2D(32,  (3,3), activation='relu', padding='same',
               input_shape=(img_rows, img_cols, channels)),
        MaxPooling2D(2, 2),

        # Block 2
        Conv2D(64,  (3,3), activation='relu', padding='same'),
        MaxPooling2D(2, 2),

        # Block 3
        Conv2D(128, (3,3), activation='relu', padding='same'),
        MaxPooling2D(2, 2),

        Flatten(),
        Dense(256, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M3_Deeper_CNN')
    model.summary()
    return model

m3 = build_m3()
m3.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m3 = m3.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m3, 'M3 — Deeper CNN')
results_m3 = evaluate_model(m3, X_test, y_test, 'M3 — Deeper CNN')

"""## M4 - CNN (Reg - Dropout)"""

# ── M4: Dropout CNN ───────────────────────────────────────────────────────────
# Architecture rationale:
#   Identical to M3 but adds dropout regularisation at two points:
#   SpatialDropout2D(0.25) after each conv block drops entire feature maps
#   rather than individual activations. This is more effective than standard
#   dropout in conv layers because adjacent pixels in a feature map are highly
#   correlated — zeroing a single pixel is easily compensated by neighbours,
#   whereas zeroing an entire map forces the network to rely on other filters.
#   Dropout(0.5) in the dense head prevents co-adaptation of learned features.
#   Comparison with M3 isolates the effect of dropout alone.

def build_m4():
    model = Sequential([
        # Block 1
        Conv2D(32,  (3,3), activation='relu', padding='same',
               input_shape=(img_rows, img_cols, channels)),
        MaxPooling2D(2, 2),
        SpatialDropout2D(0.25),

        # Block 2
        Conv2D(64,  (3,3), activation='relu', padding='same'),
        MaxPooling2D(2, 2),
        SpatialDropout2D(0.25),

        # Block 3
        Conv2D(128, (3,3), activation='relu', padding='same'),
        MaxPooling2D(2, 2),
        SpatialDropout2D(0.25),

        Flatten(),
        Dense(256, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M4_Dropout_CNN')
    model.summary()
    return model

m4 = build_m4()
m4.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m4 = m4.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m4, 'M4 — Dropout CNN')
results_m4 = evaluate_model(m4, X_test, y_test, 'M4 — Dropout CNN')

"""## M5 - CNN (Reg - BatchNorm)"""

# ── M5: BatchNorm CNN ─────────────────────────────────────────────────────────
# Architecture rationale:
#   Identical to M3 but replaces dropout with BatchNormalization after each
#   conv layer. BatchNorm normalises activations within each mini-batch,
#   stabilising the distribution of inputs to each layer during training.
#   This reduces internal covariate shift, allows higher learning rates, and
#   acts as a mild regulariser by adding noise through batch statistics.
#   Placement: after Conv, before activation (standard convention).
#   Comparing M4 vs M5 directly answers: is dropout or BatchNorm more effective
#   as a regulariser on this dataset and architecture?

def build_m5():
    model = Sequential([
        # Block 1
        Conv2D(32,  (3,3), padding='same',
               input_shape=(img_rows, img_cols, channels)),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 2
        Conv2D(64,  (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 3
        Conv2D(128, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        Flatten(),
        Dense(256, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M5_BatchNorm_CNN')
    model.summary()
    return model

m5 = build_m5()
m5.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m5 = m5.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m5, 'M5 — BatchNorm CNN')
results_m5 = evaluate_model(m5, X_test, y_test, 'M5 — BatchNorm CNN')

"""## M6 - CNN (GAP replaces Flatten)"""

# ── M6: GAP CNN ───────────────────────────────────────────────────────────────
# Architecture rationale:
#   Takes the best regulariser from M4/M5 (BatchNorm) and replaces Flatten
#   with GlobalAveragePooling2D (GAP). After the final conv block, the feature
#   map has shape (H, W, 128). Flatten unrolls this into H×W×128 values,
#   creating a massive Dense connection sensitive to object position.
#   GAP instead averages each of the 128 feature maps to a single scalar,
#   producing a compact 128-d vector regardless of spatial size. Benefits:
#   (1) dramatically fewer parameters — the Dense connection shrinks from
#   H×W×128×256 to 128×128; (2) built-in spatial invariance — a glass bottle
#   in the top-left vs bottom-right of the frame produces the same GAP output;
#   (3) reduced overfitting on small datasets.

def build_m6():
    model = Sequential([
        # Block 1
        Conv2D(32,  (3,3), padding='same',
               input_shape=(img_rows, img_cols, channels)),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 2
        Conv2D(64,  (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 3
        Conv2D(128, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        GlobalAveragePooling2D(),
        Dense(128, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M6_GAP_CNN')
    model.summary()
    return model

m6 = build_m6()
m6.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m6 = m6.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=30,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(),
    verbose=1
)

plot_history(history_m6, 'M6 — GAP CNN')
results_m6 = evaluate_model(m6, X_test, y_test, 'M6 — GAP CNN')

"""M6 GAP accuracy < M5 BatchNorm -> keep FLatten

## M7 - CNN (+ augmentation)
"""

# ── M7: Strong Augmentation CNN ───────────────────────────────────────────────
# Architecture rationale:
#   M6 (GAP head) underperformed M5 (Flatten head) on this dataset, suggesting
#   the Flatten + Dense(256) head has sufficient capacity to learn the class
#   boundaries without the spatial invariance trade-off that GAP introduces.
#   M7 therefore returns to M5's exact architecture as the stronger baseline.
#
#   The only change from M5 is the augmentation policy: light (horizontal flip
#   + 15° rotation) is replaced with strong augmentation (flip + 20° rotation
#   + zoom ±20% + brightness jitter ±20% + small translations).
#
#   Rationale for stronger augmentation:
#   With ~330 training images per class, the model is at high risk of memorising
#   specific image compositions rather than learning class-defining features.
#   Zoom simulates waste items photographed at different distances from the
#   camera. Brightness jitter replicates variable lighting conditions in a
#   recycling facility. Translations mimic off-centre framing. Together these
#   synthetically expand the effective training distribution without collecting
#   new data. Comparing M5 vs M7 isolates the effect of augmentation strength
#   on M5's architecture.

def build_m7():
    model = Sequential([
        # Block 1
        Conv2D(32,  (3,3), padding='same',
               input_shape=(img_rows, img_cols, channels)),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 2
        Conv2D(64,  (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 3
        Conv2D(128, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        Flatten(),
        Dense(256, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M7_StrongAug_CNN')
    model.summary()
    return model

m7 = build_m7()

m7.compile(optimizer='adam',
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

# Uses datagen_strong — the only difference from M5
history_m7 = m7.fit(
    datagen_strong.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=40,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(patience_es=12, patience_lr=6),
    verbose=1
)

plot_history(history_m7, 'M7 — Strong Augmentation CNN')
results_m7 = evaluate_model(m7, X_test, y_test, 'M7 — Strong Augmentation CNN')

"""Strong augmentation broke images beyond recognition

## M8 - CNN (x2 layer/block - VGG Style)
"""

# ── M8: Deep VGG-style CNN ────────────────────────────────────────────────────
# Architecture rationale:
#   M7 (strong augmentation) collapsed to ~19% accuracy — the aggressive zoom,
#   brightness jitter and translations distorted images beyond the point where
#   class-defining features remain recognisable at 96×96. This confirms that
#   light augmentation (M5) is the correct policy for this dataset.
#
#   M8 therefore builds on M5's winning configuration (BatchNorm + Flatten +
#   light augmentation) and introduces one structural change: two convolutional
#   layers per block instead of one (VGG-style double conv).
#
#   Rationale for double conv per block:
#   Two stacked 3×3 convolutions have the same effective receptive field as a
#   single 5×5 convolution but with fewer parameters and an extra non-linearity
#   between them. The additional non-linearity makes the feature detectors more
#   expressive — rather than one linear filter followed by ReLU, the network
#   applies two successive transformations before pooling. This allows each
#   block to capture richer combinations of low-level features before
#   downsampling discards spatial detail.
#   Block 1: detects edges + simple textures more thoroughly
#   Block 2: combines textures into surface patterns (corrugation, smoothness)
#   Block 3: assembles patterns into object-level representations
#   Filter progression 32 → 64 → 128 is retained from M5.
#   BatchNorm after every conv (6 total) stabilises the deeper stack.
#   Flatten + Dense(256) head retained — confirmed stronger than GAP on M6.

def build_m8():
    model = Sequential([
        # Block 1 — 32 filters × 2
        Conv2D(32, (3,3), padding='same',
               input_shape=(img_rows, img_cols, channels)),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Conv2D(32, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 2 — 64 filters × 2
        Conv2D(64, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Conv2D(64, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        # Block 3 — 128 filters × 2
        Conv2D(128, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Conv2D(128, (3,3), padding='same'),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        MaxPooling2D(2, 2),

        Flatten(),
        Dense(256, activation='relu'),
        Dense(num_classes, activation='softmax')
    ], name='M8_VGG_Style_CNN')
    model.summary()
    return model

m8 = build_m8()

m8.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

# Light augmentation — confirmed correct policy from M5 vs M7 comparison
history_m8 = m8.fit(
    datagen_light.flow(X_train, y_train, batch_size=BATCH_SIZE),
    epochs=40,
    validation_data=(X_test, y_test),
    callbacks=get_callbacks(patience_es=12, patience_lr=6),
    verbose=1
)

plot_history(history_m8, 'M8 — Deep VGG-style CNN')
results_m8 = evaluate_model(m8, X_test, y_test, 'M8 — Deep VGG-style CNN')

""""Increasing depth via double conv blocks (M8) did not improve over M5, suggesting that on a dataset of ~2,000 images, additional convolutional capacity leads to overfitting rather than better generalisation. M5's shallower architecture with BatchNorm represents the optimal depth for this data scale."

## M9 - CNN (MobileNetV2)
"""

# ── M9: MobileNetV2 — Feature Extraction (frozen backbone) ───────────────────
# Architecture rationale:
#   Models M1–M8 learn visual features from scratch on ~2,000 training images.
#   The fundamental limitation is data scarcity — ~330 images per class is
#   insufficient to learn robust, generalisable feature detectors from random
#   initialisation. Transfer learning addresses this directly.
#
#   MobileNetV2 was pretrained on ImageNet (1.2 million images, 1,000 classes).
#   Its convolutional layers already encode rich, hierarchical visual features:
#   edges and gradients in early layers, textures and object parts in later layers.
#   These features transfer well to waste classification because both domains
#   involve natural images with colour, texture, and shape cues.
#
#   In Phase 1 (M9), the entire MobileNetV2 backbone is frozen — only the new
#   classification head is trained. This is the safest approach: pretrained
#   features are preserved exactly, and the head quickly learns to map those
#   features to our 6 waste classes. training=False on the base model keeps
#   BatchNorm layers in inference mode (uses stored statistics rather than
#   batch statistics), which is critical when the backbone is frozen.
#
#   MobileNetV2 is chosen over VGG16/ResNet50 because its depthwise separable
#   convolutions are computationally lightweight — appropriate for potential
#   deployment on edge hardware in a recycling facility, and faster to train
#   on Colab's free-tier GPU.
#
#   Input preprocessing: MobileNetV2 expects pixels scaled to [-1, 1] via
#   preprocess_input — NOT [0,1]. Using the wrong normalisation silently
#   degrades accuracy because the pretrained weights were calibrated to [-1,1].
print("Reloading images with correct MobileNetV2 preprocessing...")
X_tl, y_tl = [], []

for idx, cls in enumerate(CLASSES):
    cls_path = os.path.join(DATA_DIR, cls)
    for fname in os.listdir(cls_path):
        fpath = os.path.join(cls_path, fname)
        try:
            img = tf.keras.utils.load_img(fpath, target_size=(96, 96))
            arr = tf.keras.utils.img_to_array(img)  # raw [0, 255] — NO /255
            X_tl.append(arr)
            y_tl.append(idx)
        except Exception:
            pass

# preprocess_input handles the [-1, 1] scaling internally
X_tl = tf.keras.applications.mobilenet_v2.preprocess_input(
    np.array(X_tl, dtype='float32')
)
y_tl = np.array(y_tl)

print(f"Pixel range after preprocessing: [{X_tl.min():.2f}, {X_tl.max():.2f}]")
# Should print approximately [-1.00, 1.00]

X_train_tl, X_test_tl, y_train_tl, y_test_tl = train_test_split(
    X_tl, y_tl, test_size=0.30, random_state=SEED, stratify=y_tl
)

datagen_tl = ImageDataGenerator(
    horizontal_flip=True,
    rotation_range=15
)
datagen_tl.fit(X_train_tl)

print(f"TL train: {len(X_train_tl)}  |  TL test: {len(X_test_tl)}")

def build_m9_fixed():
    base_model = tf.keras.applications.MobileNetV2(
        input_shape=(96, 96, 3),
        include_top=False,
        weights='imagenet'
    )
    base_model.trainable = False

    inputs  = Input(shape=(96, 96, 3))
    x       = base_model(inputs, training=False)
    x       = GlobalAveragePooling2D()(x)
    x       = Dense(256, activation='relu')(x)   # wider than before
    x       = Dropout(0.4)(x)
    x       = Dense(128, activation='relu')(x)   # two-stage head
    x       = Dropout(0.3)(x)
    outputs = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs, outputs, name='M9_MobileNetV2_Fixed')
    model.summary()
    return model, base_model

m9, base_model_m9 = build_m9_fixed()

m9.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m9 = m9.fit(
    datagen_tl.flow(X_train_tl, y_train_tl, batch_size=BATCH_SIZE),
    epochs=20,
    validation_data=(X_test_tl, y_test_tl),
    callbacks=get_callbacks(patience_es=6, patience_lr=3),
    verbose=1
)

plot_history(history_m9, 'M9 — MobileNetV2 Feature Extraction (Fixed)')
results_m9 = evaluate_model(m9, X_test_tl, y_test_tl,
                             'M9 — MobileNetV2 Feature Extraction')

"""## M10 - CNN (MobileNetV2 Fine-tuned)"""

# ── M10: MobileNetV2 Fine-Tuning ─────────────────────────────────────────────
# The frozen backbone in M9 achieved 81% — a marginal improvement over M5's
# 80.3%. This suggests the pretrained features, while useful, are not perfectly
# calibrated for waste classification. Fine-tuning the top layers allows the
# network to adapt high-level feature detectors toward waste-specific patterns:
# the translucency of glass, metallic sheen of cans, corrugation of cardboard.
#
# Top 30 layers are unfrozen — these encode the most task-specific, abstract
# representations in the backbone. Bottom layers remain frozen as they detect
# universal low-level features (edges, gradients) needing no adaptation.
#
# Learning rate drops from 1e-3 to 1e-5 — essential to prevent large gradient
# updates from destroying the pretrained weights. Small nudges adapt the
# features; large updates would reset them to random noise.

print("Unfreezing top 30 layers of MobileNetV2 backbone...")

base_model_m9.trainable = True
for layer in base_model_m9.layers[:-30]:
    layer.trainable = False

trainable_count = sum(1 for l in base_model_m9.layers if l.trainable)
print(f"Trainable backbone layers : {trainable_count} / {len(base_model_m9.layers)}")

# Recompile at fine-tuning learning rate
m9.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
           loss='sparse_categorical_crossentropy',
           metrics=['accuracy'])

history_m10 = m9.fit(
    datagen_tl.flow(X_train_tl, y_train_tl, batch_size=BATCH_SIZE),
    epochs=20,
    validation_data=(X_test_tl, y_test_tl),
    callbacks=get_callbacks(patience_es=8, patience_lr=4),
    verbose=1
)

# Combined plot — shows full training arc from M9 head training → M10 fine-tune
def plot_combined_history(h1, h2, model_name):
    acc   = h1.history['accuracy']     + h2.history['accuracy']
    val   = h1.history['val_accuracy'] + h2.history['val_accuracy']
    loss  = h1.history['loss']         + h2.history['loss']
    vloss = h1.history['val_loss']     + h2.history['val_loss']
    boundary = len(h1.history['accuracy'])

    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    for ax, train, val_data, title in zip(
        axes,
        [acc, loss], [val, vloss],
        [f'{model_name} — Accuracy', f'{model_name} — Loss']
    ):
        ax.plot(train,    label='Train')
        ax.plot(val_data, label='Validation')
        ax.axvline(boundary, color='gray', linestyle='--',
                   label='Fine-tune start')
        ax.set_title(title)
        ax.set_xlabel('Epoch')
        ax.legend()

    plt.tight_layout()
    plt.show()

plot_combined_history(history_m9, history_m10, 'M9 → M10 MobileNetV2')
results_m10 = evaluate_model(m9, X_test_tl, y_test_tl,
                              'M10 — MobileNetV2 Fine-Tuning')

"""## Model comparison"""

all_results = [results_m1, results_m2, results_m3, results_m4, results_m5,
               results_m6, results_m7, results_m8, results_m9, results_m10]

summary_df = pd.DataFrame([{
    'Model'    : r['model'],
    'Test Acc' : round(r['accuracy'], 4),
    'Test Loss': round(r['loss'],     4),
} for r in all_results])

print("\n" + "="*65)
print("               MODEL COMPARISON SUMMARY")
print("="*65)
print(summary_df.to_string(index=False))

colors = ['#C0392B', '#E67E22', '#F1C40F', '#2ECC71',
          '#1ABC9C', '#3498DB', '#2980B9', '#8E44AD',
          '#D35400', '#1A5276']

fig, ax = plt.subplots(figsize=(14, 6))
bars = ax.bar(range(len(summary_df)), summary_df['Test Acc'],
              color=colors, edgecolor='black', width=0.6)
ax.set_xticks(range(len(summary_df)))
ax.set_xticklabels(summary_df['Model'], rotation=25, ha='right', fontsize=9)
ax.set_ylim(0, 1.05)
ax.set_ylabel('Test Accuracy')
ax.set_title('Model Comparison — Test Accuracy (M1 → M10)')
for bar, val in zip(bars, summary_df['Test Acc']):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{val:.4f}', ha='center', va='bottom',
            fontweight='bold', fontsize=8)
plt.tight_layout()
plt.show()

all_results = [results_m1, results_m2, results_m3, results_m4, results_m5,
               results_m6, results_m7, results_m8, results_m9, results_m10]

summary_df_full = pd.DataFrame([{    'Model'          : r['model'],
    'Test Acc'       : round(r['accuracy'], 4),
    'Test Loss'      : round(r['loss'],     4),
    'Macro Precision': round(r['report']['macro avg']['precision'], 4),
    'Macro Recall'   : round(r['report']['macro avg']['recall'], 4),
    'Macro F1'       : round(r['report']['macro avg']['f1-score'], 4),
} for r in all_results])

display(summary_df_full)

# Extract report and confusion matrix for M10
report_m10 = results_m10['report']

# 1. Performance by class table
class_data = {cls: report_m10[cls] for cls in CLASSES}
m10_performance_df = pd.DataFrame(class_data).transpose()[['precision', 'recall', 'f1-score', 'support']]

print("--- M10: Performance by Class ---")
display(m10_performance_df)

# 2. Identify worst class and show confusion row
worst_class_m10 = min({cls: report_m10[cls]['f1-score'] for cls in CLASSES}, key=lambda x: report_m10[x]['f1-score'])
worst_idx = CLASSES.index(worst_class_m10)

# Re-calculate or retrieve predictions to get confusion matrix for M8
y_pred_m10 = results_m10['y_pred']
cm_m10 = confusion_matrix(y_test, y_pred_m10, normalize='true')

print(f"\n--- Confusion Row for Worst Class: '{worst_class_m10}' ---")
confusion_row = pd.DataFrame([cm_m10[worst_idx]], columns=CLASSES, index=[f"True {worst_class_m10}"])
display(confusion_row)